import { useEffect, useRef } from 'react';
import { Printer, X } from 'lucide-react';
import type { BriefAlternative, BriefMetric, RunResult } from '../types/domain';
import { safeSourceUrl } from '../utils/format';

const quantity = (value: number | null | undefined) => value == null ? 'Unknown' : value.toLocaleString('en-US', { maximumFractionDigits: 6 });
const percentage = (value: number | null) => value === null ? 'Unknown' : value.toLocaleString('en-US', { style: 'percent', maximumFractionDigits: 2 });
const known = (value: boolean | null) => value === null ? 'Unknown' : value ? 'Yes' : 'No';
const labels: Record<string, string> = { e_it_mwh: 'Annual IT electricity', e_facility_mwh: 'Annual facility electricity', c_electricity_tonnes: 'Annual electricity emissions', w_site_m3: 'Annual site water consumption', w_electricity_m3: 'Annual generation water consumption', w_site_withdrawal_m3: 'Annual site water withdrawal' };
const units: Record<string, string> = { e_facility_mwh: 'MWh/year', c_electricity_tonnes: 'tonnes CO₂e/year', w_site_m3: 'm³/year', w_electricity_m3: 'm³/year' };
const measured = (metric: BriefMetric | undefined) => !metric || metric.value === null || metric.status === 'unknown' ? 'Unknown' : `${typeof metric.value === 'number' ? quantity(metric.value) : metric.value} ${metric.unit}`;
const center = (value: { lat: number; lon: number }) => `${quantity(value.lat)}, ${quantity(value.lon)}`;
const key = (value: BriefAlternative) => `${value.region_id}/${value.grid_id}/${value.design_id}/${value.scenario_id}`;

export function DecisionBrief({ result, selectedRegionId, onClose }: { result: RunResult; selectedRegionId?: string | null; onClose: () => void }) {
  const panel = useRef<HTMLElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; panel.current?.querySelector<HTMLButtonElement>('button[aria-label="Close decision brief"]')?.focus(); return () => { if (previous?.isConnected) previous.focus(); }; }, []);
  const brief = result.decisionBrief;
  const recommendation = brief?.recommendation;
  const noRegion = recommendation?.status === 'NO_QUALIFYING_REGION';
  const alternatives = brief && recommendation ? (noRegion ? brief.alternatives : [recommendation, ...brief.alternatives.filter(value => key(value) !== key(recommendation))]) : [];
  const metricIds = [...new Set(alternatives.flatMap(value => value.metrics.map(metric => metric.id)))];
  return <section ref={panel} className="decision-brief-dialog" role="dialog" aria-modal="true" aria-label="Decision brief" onKeyDown={event => {
    if (event.key === 'Escape') { event.stopPropagation(); onClose(); return; }
    if (event.key !== 'Tab') return;
    const focusable = [...(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], summary') ?? [])].filter(element => { const closed = element.closest('details:not([open])'); return !closed || closed.querySelector(':scope > summary') === element; });
    const first = focusable[0], last = focusable.at(-1);
    if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
    else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
  }}>
    <header className="brief-heading"><div><p className="micro-label">Saved model evidence · six deliverables</p><h2>Decision brief</h2></div><div className="brief-actions">{brief && <button className="button secondary" onClick={() => window.print()}><Printer size={16} />Print decision brief</button>}<button className="icon-button" aria-label="Close decision brief" onClick={onClose}><X size={18} /></button></div></header>
    <div className="brief-content">{!brief ? <div className="brief-unavailable"><h3>No verified decision brief is available</h3><p>{result.decisionBriefUnavailableReason ?? 'This saved response predates the verified submission brief. Its map, quantities and existing exports remain available.'}</p><p className="quiet">Run {result.runId} · {result.scenarioId}. An unavailable brief is not a finding that no geography qualifies.</p></div> : <>
      {(brief.data_mode === 'synthetic' || result.demo) && <p className="brief-demo">DEMO DATA · Synthetic software fixture</p>}
      <p className="brief-interpretation">{brief.interpretation}</p>
      <dl className="brief-record"><dt>Run / external context</dt><dd>{brief.run_id} / {result.scenarioId} · physical scenario {brief.scenario_id}</dd><dt>Analyzed coverage</dt><dd>{brief.scope} · {quantity(brief.analyzed_cell_count)} cells</dd><dt>Recorded grid resolution</dt><dd>{quantity(brief.resolution_m)} m</dd><dt>Facility assumption</dt><dd>{quantity(brief.facility.peak_it_power_mw)} MW peak IT · {percentage(brief.facility.average_it_load_factor)} average load · opening {brief.facility.target_opening_year ?? 'Unknown'} · {quantity(brief.facility.operating_lifetime_years)} operating years · {quantity(brief.facility.hours_in_modeled_year)} modeled hours/year</dd></dl>
      {selectedRegionId && <p className="brief-selection">Selected region: {selectedRegionId}. The brief retains the backend recommendation and stored alternative ordering.</p>}
      <section className="brief-section"><h3>1. Investigation geography</h3><span className="status-badge conditional">{noRegion ? 'No qualifying investigation region' : recommendation!.status === 'QUALIFYING_INVESTIGATION' ? 'Qualifying investigation region' : 'Conditional investigation region'}</span><p>{recommendation!.rationale}</p>
        {!noRegion && <><h4>{recommendation!.geographic_label ?? recommendation!.region_id ?? 'Geographic label unavailable'}</h4><p>Search region {recommendation!.region_id ?? 'Unknown'} · representative cell {recommendation!.grid_id ?? 'Unknown'}<br />{recommendation!.design_id ?? 'Unknown'} · {recommendation!.scenario_id ?? 'Unknown'}<br />Stored representative alternative rank {quantity(recommendation!.rank)} · score {quantity(recommendation!.score)} / 100</p>{recommendation!.centroid && <p>Representative cell center: {center(recommendation!.centroid)} (latitude, longitude).</p>}{recommendation!.region_centroid && <p>Search region center: {center(recommendation!.region_centroid)} (latitude, longitude).</p>}<p>Region area: {quantity(recommendation!.region_area_km2)} km² · {quantity(recommendation!.region_cell_count)} member cells. Cell and region centers identify geographic evidence; neither is an approved construction parcel.</p></>}
      </section>
      <section className="brief-section"><h3>2. Decision framework</h3><p>Archived profile {brief.framework.profile_id} · {brief.framework.weighting_method} preferences. Weights, normalized scores and contributions below are stored backend results.</p><p>{brief.framework.method}</p><p>{brief.framework.missing_data_policy}</p>
        <div className="brief-table-scroll"><table className="brief-table"><caption>Declared criteria and representative score contributions</caption><thead><tr><th>Criterion / role</th><th>Direction / unit</th><th>Weight</th><th>Fixed reference bounds</th><th>Stored score</th><th>Stored contribution</th></tr></thead><tbody>{brief.framework.criteria.map(value => <tr key={value.metric_id}><th scope="row">{value.label}<small>{value.role}</small></th><td>{value.direction}<small>{value.unit}</small></td><td>{percentage(value.weight)}</td><td>{quantity(value.reference_low)} – {quantity(value.reference_high)}</td><td>{quantity(value.normalized_score)}</td><td>{quantity(value.contribution)}</td></tr>)}</tbody></table></div>
        <details><summary>Criterion basis and excluded dimensions</summary>{brief.framework.criteria.map(value => <p key={value.metric_id}><strong>{value.label}</strong> · {value.basis}: {value.rationale}</p>)}<ul>{brief.framework.excluded_criteria.map(value => <li key={value}>{value}</li>)}</ul></details>
      </section>
      <section className="brief-section"><h3>3. Evidence and assumptions</h3><p>{brief.facility.basis}: {brief.facility.rationale}</p><ul>{brief.evidence.assumptions.map(value => <li key={value}>{value}</li>)}</ul>
        <div className="brief-table-scroll"><table className="brief-table"><caption>Implemented, acquired and analyzed source evidence remain separate</caption><thead><tr><th>Source</th><th>Implemented / acquired / analyzed</th><th>Analyzed cells</th><th>Version / period</th></tr></thead><tbody>{brief.evidence.sources.map(value => { const url = safeSourceUrl(value.source_url); return <tr key={value.source_id}><th scope="row">{url ? <a href={url} target="_blank" rel="noopener noreferrer">{value.source_id}</a> : value.source_id}<small>{value.status}</small></th><td>{known(value.implemented)} / {known(value.acquired)} / {known(value.analyzed)}</td><td>{quantity(value.analyzed_cells)}</td><td>{value.source_version || 'Unknown'} / {value.data_year}<small>Retrieved: {value.retrieved_at ?? 'Unknown'}</small></td></tr>; })}</tbody></table></div>
        <details><summary>Verified input identities</summary><pre>{JSON.stringify(brief.evidence.input_hashes, null, 2)}</pre></details>
      </section>
      <section className="brief-section"><h3>4. Resource impact</h3><p>{brief.impact.boundary}</p>{brief.impact.total_water_consumption && <article className="brief-impact-comparison"><h4>Total site and generation-water consumption</h4><strong>{measured(brief.impact.total_water_consumption)}</strong><p className="quiet">{brief.impact.total_water_consumption.status} · confidence {brief.impact.total_water_consumption.confidence}</p>{brief.impact.total_water_consumption.missing_reason && <p>{brief.impact.total_water_consumption.missing_reason}</p>}</article>}
        {alternatives.length > 0 && <div className="brief-table-scroll"><table className="brief-table"><caption>Stored representative alternatives · design and physical scenario stay paired</caption><thead><tr><th>Quantity</th>{alternatives.map(value => <th key={key(value)} scope="col">{value.design_id}<small>{value.grid_id} · {value.scenario_id} · stored rank {quantity(value.rank)}</small></th>)}</tr></thead><tbody>{metricIds.map(id => <tr key={id}><th scope="row">{labels[id] ?? id}</th>{alternatives.map(value => { const metric = value.metrics.find(metric => metric.id === id); return <td key={key(value)}>{measured(metric)}<small>{metric?.status ?? 'unknown'} · confidence {metric?.confidence ?? 'unknown'}{metric?.missing_reason ? ` · ${metric.missing_reason}` : ''}</small></td>; })}</tr>)}</tbody></table></div>}
        {brief.impact.cooling_comparisons.map((value, index) => <article className="brief-impact-comparison" key={`${value.grid_id}/${value.scenario_id}/${index}`}><h4>Same-cell cooling comparison</h4><p>{value.reference_design_id} minus {value.alternative_design_id} · {value.grid_id} · {value.scenario_id}. Signed differences use the backend’s declared order.</p><dl className="brief-record">{Object.entries(value.reference_minus_alternative).map(([id, difference]) => <div key={id}><dt>{labels[id] ?? id}</dt><dd>{difference === null ? 'Unknown' : `${quantity(difference)} ${units[id] ?? 'unit unreported'}`}</dd></div>)}</dl><p className="quiet">{value.basis}</p></article>)}
        <ul className="brief-unknowns">{brief.impact.unknowns.map(value => <li key={value.id}><strong>{value.id}: Unknown</strong><br />{value.missing_reason}</li>)}</ul>
      </section>
      <section className="brief-section"><h3>5. Risks and verification</h3>{brief.risks.length ? <div className="brief-table-scroll"><table className="brief-table"><caption>Recorded screening evidence and required investigation actions</caption><thead><tr><th>Requirement / outcome</th><th>Evidence limit</th><th>Action</th></tr></thead><tbody>{brief.risks.map((value, index) => <tr key={`${value.requirement}/${index}`}><th scope="row">{value.requirement}<small>{value.outcome}</small></th><td>{value.missing_reason ?? 'See recorded screening evidence.'}</td><td>{value.action}</td></tr>)}</tbody></table></div> : <p>No additional risk actions were supplied; absence does not establish parcel feasibility.</p>}</section>
      <section className="brief-section"><h3>6. Operating vision</h3><p className="brief-plan-note">Proposed project plan · these actions are investigation and operating commitments to evaluate, not measured outcomes or forecasts.</p><ol className="brief-vision">{brief.implementation_vision.map((value, index) => <li key={`${value.period}/${index}`}><p className="micro-label">{value.period}</p><h4>{value.label}</h4><ul>{value.actions.map(action => <li key={action}>{action}</li>)}</ul><p><strong>Evidence gate:</strong> {value.evidence_gate}</p></li>)}</ol></section>
      <section className="brief-section"><h3>Limits of the submission</h3><ul>{brief.limitations.map(value => <li key={value}>{value}</li>)}</ul><p className="quiet">Brief schema {brief.schema_version} · {brief.data_mode}. The browser displays recorded quantities and decisions; it does not compute scores or select an external scenario.</p></section>
    </>}</div>
  </section>;
}
