import { afterEach,describe,it,expect,vi } from 'vitest';
import { realApi,isDemoMode } from './client';
import { DEMO_CONFIG,demoLayer,demoRun } from '../mocks/data';
function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});}
afterEach(()=>vi.unstubAllGlobals());
describe('real model transport',()=>{
  it('submits inputs and reads a completed backend job and authoritative results',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(json({job_id:'job1'})).mockResolvedValueOnce(json({id:'job1',state:'COMPLETE',stage:'Validation complete',run_id:'REAL_RUN',error:null})).mockResolvedValueOnce(json({...demoRun(),run_id:'REAL_RUN',demo:false}));vi.stubGlobal('fetch',fetchMock);const onProgress=vi.fn();const result=await realApi.search(DEMO_CONFIG,onProgress);expect(fetchMock.mock.calls[0][0]).toBe('/api/search');expect(JSON.parse(fetchMock.mock.calls[0][1].body)).toMatchObject({facility:{peak_it_power_mw:100,average_load_percent:80}});expect(onProgress).toHaveBeenCalledWith(expect.objectContaining({state:'COMPLETE'}));expect(result.runId).toBe('REAL_RUN');expect(result.demo).toBe(false);});
  it('does not silently fall back to synthetic data on service failure',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new TypeError('Network error')));expect(isDemoMode).toBe(false);await expect(realApi.capabilities()).rejects.toThrow('Model service unavailable');});
  it('preserves backend errors for preference consistency review',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json({error:'Your priorities require review.'},422)));await expect(realApi.search(DEMO_CONFIG)).rejects.toThrow('priorities require review');});
  it('caches unchanged optional layer responses',async()=>{const fetchMock=vi.fn().mockImplementation(async()=>json(demoLayer('water')));vi.stubGlobal('fetch',fetchMock);const a=await realApi.layer('water','CACHE_TEST','current');const b=await realApi.layer('water','CACHE_TEST','current');expect(a).toBe(b);expect(fetchMock).toHaveBeenCalledTimes(1);await realApi.layer('water','CACHE_TEST','bau_2050');expect(fetchMock).toHaveBeenCalledTimes(2);});
  it('passes cancellation to fetch and never returns a cached value after abort',async()=>{const controller=new AbortController();controller.abort();vi.stubGlobal('fetch',vi.fn((_url,opts)=>{expect(opts.signal.aborted).toBe(true);return Promise.reject(new DOMException('Aborted','AbortError'));}));await expect(realApi.run('X','current',controller.signal)).rejects.toMatchObject({name:'AbortError'});await expect(realApi.layer('water','CACHE_TEST','current',undefined,controller.signal)).rejects.toMatchObject({name:'AbortError'});});
});
